### ISSUE TITLE
Please consider a nix service handler

### ISSUE THREAD

**Issue by blaggacao** [ttacon/glorious#49]
https://search.nixos.org/options?channel=20.09&from=0&size=30&sort=relevance&query=service

More than 7953 pre-configured services based on systemd.

bread-crumb trails:
- https://github.com/numtide/devshell/issues/47
- https://github.com/NixOS/rfcs/pull/78

**Comment by ttacon** [comment]
Hi @blaggacao , happy to consider such a handler - would you be able to add a little more detail to what you have in mind?

**Comment by blaggacao** [comment]
Hi @ttacon thanks for acking this feedback. Currently, there is a discussion in rfc78 about carving out the low hanging fruits of nix services declarations and make them independent from _systemd_ over time. I consider such transition is a fair pre-requisite for any attempt on this proposal to succeed.

Over at the nascent numtide/devshell community (which leverages the reproducible packaging side of the nix ecosystem for dev environments), we had a discussion once about a complementary service manager implementation for development environments.

I think a triangle of common interests with interesting potential would align with _ttacon/glourious_ goals, once:
- _numtide/devshell_ is out of alpha (1-2 years?)
- rfc78 on the nix side culminated (2-3 years?)

... long term.
